feat: add loading pulse effect on country view
jst-seminar-rostlab-tum/wfp-hunger-map pull request #110
Opened 2024-12-06 10:47 UTC by ArmanpreetGhotra

Add pulse animation to the country view in nutrition, fcs and ipc. A little note: i tried to put the colors of the animation in the tailwind.config.js, but it was not working.

2024-12-06 11:34 UTC, bohdangarchu requested changes
great job!!

2024-12-06 11:34 UTC, bohdangarchu commented on src/components/Map/FcsChoropleth.tsx
> +          } // Explicitly type as FeatureCollection
remove comment

2024-12-06 11:34 UTC, bohdangarchu commented on src/components/Map/FcsChoropleth.tsx
> +            fillColor: '#338ef7',
use tailwind colors with `hsl(var(--nextui-xxx))`

2024-12-06 11:34 UTC, bohdangarchu commented on src/components/Map/IpcMap/IpcChoropleth.tsx
> +        <GeoJSON
Maybe you could extract this into a CountrySkeleton component and pass data and color there?

2024-12-07 12:27 UTC, bohdangarchu approved these changes

2024-12-08 09:51 UTC, marinovl7 approved these changes
LGTM!

2024-12-08 09:51 UTC, merged