fix: adjust sidebar height
jst-seminar-rostlab-tum/wfp-hunger-map pull request #133
Opened 2024-12-14 12:15 UTC by georgi4444

2024-12-14 17:47 UTC, Tschonti commented
unfortunately, the alerts are still hidden on my 15.6" laptop. I think those buttons are way more important than disclaimer etc. Maybe we should collapse the links on the bottom? Or make the whole sidebar scrollable?
![image](https://github.com/user-attachments/assets/eac5b8b5-976f-436e-a9a9-b8caf4c1da98)

2024-12-15 13:59 UTC, marinovl7 requested changes
Agree with Samuel, I would also make the whole sidebar scrollable

2024-12-22 13:19 UTC, Tschonti commented
Much better, but can we still make the whole sidebar scrollable? I think with this it looks good on most screens, but just in case someone looks at it on a really small screen, I think we should still hide the links before the alerts

2024-12-22 18:48 UTC, georgi4444 commented
> Much better, but can we still make the whole sidebar scrollable? I think with this it looks good on most screens, but just in case someone looks at it on a really small screen, I think we should still hide the links before the alerts

Done this as well now

2025-01-07 06:34 UTC, merged