Feature/f 35 pdf preview implementation
jst-seminar-rostlab-tum/wfp-hunger-map pull request #14
Opened 2024-11-05 11:12 UTC by bohdangarchu

@Tschonti please approve if it is ok that I add `"react/jsx-no-bind": "off"` to our linter config. I think we need it for defining functions inside components like `handleScroll` (see `PdfViewer.tsx`).

2024-11-05 11:14 UTC, bohdangarchu commented on src/styles/globals.css
> +canvas.react-pdf__Page__canvas {
we need to use css here to add padding between pages

2024-11-06 20:15 UTC, marinovl7 requested changes
Overall great job! Take a look at my comments, just smal code styling issues I found. Also few things to add here: 

1. Can you please add the download PDF Functionality?
2. Can you think how we can get the documents from this endpoint `
https://static.hungermapdata.org/insight-reports/latest/country.json` and display them in the previewer? 
3. add border to the navbar and the color could be like light gray in light mode and dark grey in dark mode.

But overall quality and functionality is great! Good job!

2024-11-07 12:15 UTC, bohdangarchu commented on tailwind.config.js
> +            secondary: '#666666',
this corresponds to our secondary color used in figma designs

2024-11-08 15:41 UTC, marinovl7 approved these changes
Great Job!

2024-11-08 15:41 UTC, merged