Feature/f 183 categorical chart minor improvements
jst-seminar-rostlab-tum/wfp-hunger-map pull request #155
Opened 2024-12-21 15:46 UTC by plaume8

- all solved and implemented minor todos are described in [F-183](https://linear.app/world-food-programme-wfp/issue/F-183/categorical-chart-minor-improvements)
- please especially check/review the selected static and increased height of the line charts in the "Comparison Portal".

2025-01-07 06:41 UTC, marinovl7 commented
Merge Conflicts

2025-01-07 10:22 UTC, bohdangarchu requested changes
When selecting a country on comparison portal charts are rerendered multiple times, while on develop it only happens once. Could you check this please?

2025-01-09 11:23 UTC, plaume8 commented
> When selecting a country on comparison portal charts are rerendered multiple times, while on develop it only happens once. Could you check this please?

could not find a quick fix -> creates a new issue [f-223](https://linear.app/world-food-programme-wfp/issue/F-223/bug-chart-multiple-rerendering) -> such that this issue can be merged as soon as possible

2025-01-10 08:19 UTC, bohdangarchu requested changes

2025-01-10 08:19 UTC, bohdangarchu commented on src/components/Charts/helpers/ChartContainer.tsx
> +      setChartKey((prev) => prev + 1); // forces chart to remount -> chart animation will be re-triggered
I also checked other graphs and noticed that they are now rendered twice every time. I feel like this approach of resetting chart key is a bit problematic bc it triggers additional animation. 

I just tested this out and if you remove this line from both useEffects everything seems to work fine (incl. theme switch).

2025-01-10 08:22 UTC, bohdangarchu commented
> > When selecting a country on comparison portal charts are rerendered multiple times, while on develop it only happens once. Could you check this please?
> 
> could not find a quick fix -> creates a new issue [f-223](https://linear.app/world-food-programme-wfp/issue/F-223/bug-chart-multiple-rerendering) -> such that this issue can be merged as soon as possible

This issue is introduced in this pr so in my opinion it is better to fix it here

2025-01-10 14:26 UTC, plaume8 commented on src/components/Charts/helpers/ChartContainer.tsx
> +      setChartKey((prev) => prev + 1); // forces chart to remount -> chart animation will be re-triggered
you are absolutely right, I totally forget about this change -> I fixed it -> now only the "model type switch" is using this extra setChartKey functionallity

2025-01-10 14:45 UTC, bohdangarchu approved these changes

2025-01-11 10:44 UTC, merged