feat: implement rainfall and vegetation maps
jst-seminar-rostlab-tum/wfp-hunger-map pull request #41
Opened 2024-11-18 19:59 UTC by jschoedl

Due to the CORS of the WFP APIs, the map doesn't work in the demo. During development I used a Plug-In that temporarily disabled the CORS guidelines.
![Bildschirmfoto vom 2024-11-18 20-56-33](https://github.com/user-attachments/assets/b071ac8f-c07f-4ea2-abfa-389f2926230e)
![Bildschirmfoto vom 2024-11-18 20-56-47](https://github.com/user-attachments/assets/8a6d63da-63dc-4358-9cfb-5c9eb99876c0)
![Bildschirmfoto vom 2024-11-18 20-57-04](https://github.com/user-attachments/assets/5f006d66-5a7d-4de4-8acd-035ea9029d12)
![Bildschirmfoto vom 2024-11-18 20-56-56](https://github.com/user-attachments/assets/10dcc7c6-897f-4a1c-a3e1-eb1864f045e1)

2024-11-18 20:09 UTC, marinovl7 approved these changes
LGTM for me! @Lukas0912 will do the final approval and merge!

2024-11-18 20:44 UTC, Lukas0912 requested changes
Very nice improvement of the layer system from before, I would just suggest to add another layer on top with the deactivated non interactive countries and change the base layer to a uniformly colored base layer. Right now the differentiation of selectable and non selectable countries is not possible anymore since the overlay isn't transparent.

2024-11-18 20:44 UTC, Lukas0912 commented on src/operations/map/MapOperations.ts
>                'fill-opacity': ['case', ['boolean', ['feature-state', 'hover'], false], 0.7, 1],
I think this line doesn't have any effect anymore now

2024-11-19 09:29 UTC, jschoedl commented
![Bildschirmfoto vom 2024-11-19 10-26-40](https://github.com/user-attachments/assets/52a59c90-dbab-49f9-902b-3b3f8caf3998)
![Bildschirmfoto vom 2024-11-19 10-26-48](https://github.com/user-attachments/assets/666eb1b6-1cf7-4159-aded-2ef3b3d8edba)

2024-11-19 10:29 UTC, merged